package com.example.agent.domain.event;

/**
 * 事件类型枚举，定义系统内事件语义。
 */
public enum EventType {
    WORKFLOW_STARTED,
    WORKFLOW_COMPLETED,
    AGENT_STARTED,
    AGENT_COMPLETED,
    ERROR_OCCURRED,
    LLM_PROMPT,
    LLM_PARTIAL,
    LLM_OUTPUT,
    TOOL_INVOKED,
    TOOL_OBSERVATION,
    TOOL_ERROR,
    DELEGATION,
    TEAM_RECRUITED,
    TEAM_RETIRED,
    MESSAGE_SENT,
    MESSAGE_RECEIVED,
    ROLE_ASSIGNED,
    PROGRESS,
    DATA_PROCESSING,
    WAITING,
    TEAM_STATUS,
    WORKSPACE_UPDATED,
    APPROVAL_REQUESTED,
    APPROVAL_DECISION,
    MEMORY_SAVED,
    SCHEDULE_TRIGGERED,
    AUTH_FAILED,
    BUDGET_THRESHOLD
}
